// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class Kit
{
    public int KitId { get; set; }

    public string KitName { get; set; }

    public byte[] KitImage { get; set; }

    public int? CategoryId { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public int? KitStatusId { get; set; }

    public byte[] Lab { get; set; }

    public virtual Category Category { get; set; }

    public virtual KitStatus KitStatus { get; set; }

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();
}