// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class KitStatus
{
    public int KitStatusId { get; set; }

    public string KitStatusName { get; set; }

    public virtual ICollection<Kit> Kits { get; set; } = new List<Kit>();
}