// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class Order
{
    public int OrdersId { get; set; }

    public int? UsersId { get; set; }

    public string ReceiveName { get; set; }

    public string ReceivePhoneNumbers { get; set; }

    public DateTime? OrdersDate { get; set; }

    public byte[] OrdersImage { get; set; }

    public string StreetAddress { get; set; }

    public string CompanyName { get; set; }

    public string Apartment { get; set; }

    public string City { get; set; }

    public string Postcode { get; set; }

    public decimal? TotalAmount { get; set; }

    public int? StatusId { get; set; }

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();

    public virtual OrdersStatus Status { get; set; }

    public virtual User Users { get; set; }
}