// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class OrdersStatus
{
    public int OrdersStatusId { get; set; }

    public string OrdersStatusName { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}