// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class UsersStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}