// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kitkitssss.Server.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CompanyName { get; set; }

    public string Country { get; set; }

    public string StreetAddress { get; set; }

    public string Apartment { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Token { get; set; }

    public int? RoleId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? StatusId { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Role Role { get; set; }

    public virtual UsersStatus Status { get; set; }
}